#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    activate:
      on-profile:
  web:
    resources:
      add-mappings: true

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
#    operations-sorter: method
#    #custom path for api docs
#    url: /doc/openapi.json